### ISSUE TITLE
Homophones

### ISSUE THREAD

**Issue by anseljh** [kemitchell/american-legal-homonyms#6]
@kemitchell, what do you think would be a good way to deal with homophones?

I just ran into this real-life example in a complaint: a cause of action for "Tortuous Interference with Contract". Maybe it was bad, but...probably didn't involve an iron maiden.

**Comment by kemitchell** [comment]
I'm guessing that was either a typo, or a typo and automatic spelling correction.

Not sure we want to get into the better spellchecker business.  I suppose you could run a legal dictionary word list against a general word list with Levenshtein distance and tag the matches.  But I'm guessing making something reliable becomes a datasets and statistics kind of project.

**Comment by anseljh** [comment]
Reasonable!
